---
- hosts: localhost
  gather_facts: false
  include_vars:
    - vars.yml
    

  tasks:
    - name: Create new incident
      servicenow.itsm.incident:
        state: new
        short_description: Demo incident
